/*
 * This file was generated by the Gradle 'init' task.
 */
val koinVersion = "2.2.2"


plugins {
    id("javalin.example.kotlin-application-conventions")
}


repositories {
    jcenter()
}

dependencies {

    // submodules
    implementation(project(":delivery"))
    implementation(project(":business"))

    // micrometer
    implementation("io.micrometer:micrometer-registry-prometheus:latest.release")
    implementation("io.micrometer:micrometer-core:latest.release")
    implementation("org.apache.commons:commons-lang3:3.0")

    //javalin
    implementation("io.javalin:javalin:3.12.0")


    // Koin
    implementation("org.koin:koin-core:$koinVersion")
    implementation("org.koin:koin-core-ext:$koinVersion")
    testImplementation("org.koin:koin-test:$koinVersion")

    // jackson
    implementation("com.fasterxml.jackson.core:jackson-databind:2.0.1")

}

application {
    // Define the main class for the application.
    mainClass.set("javalin.example.list.AppKt")
}

tasks.register<Jar>("uberJar") {
    archiveClassifier.set("uber")

    manifest {
        attributes(hashMapOf("Main-Class" to "javalin.example.list.AppKt"))
    }

    from(sourceSets.main.get().output)

    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}